export const Data = [
    {
        "id": 1,
        "organization": "Innojam",
        "value": "$2.51",
        "person": "Viva",
        "date": "1/15/2018",
        "stage": 1,
        "status": 0
    }, {
        "id": 2,
        "organization": "Zoozzy",
        "value": "$4.12",
        "person": "Stim",
        "date": "5/7/2018",
        "stage": 0,
        "status": 0
    }, {
        "id": 3,
        "organization": "Devcast",
        "value": "$9.60",
        "person": "Otcom",
        "date": "4/5/2018",
        "stage": 0,
        "status": 1
    }, {
        "id": 4,
        "organization": "Bubblemix",
        "value": "$1.44",
        "person": "Konklab",
        "date": "6/5/2018",
        "stage": 0,
        "status": 1
    }, {
        "id": 5,
        "organization": "Zava",
        "value": "$4.41",
        "person": "Bitchip",
        "date": "2/9/2018",
        "stage": 1,
        "status": 1
    }, {
        "id": 6,
        "organization": "Zoomcast",
        "value": "$7.63",
        "person": "Mat Lam Tam",
        "date": "2/2/2018",
        "stage": 3,
        "status": 0
    }, {
        "id": 7,
        "organization": "Wikido",
        "value": "$1.46",
        "person": "Opela",
        "date": "8/8/2018",
        "stage": 4,
        "status": 1
    }, {
        "id": 8,
        "organization": "Photospace",
        "value": "$4.08",
        "person": "Voltsillam",
        "date": "11/2/2017",
        "stage": 0,
        "status": 1
    }, {
        "id": 9,
        "organization": "Skyble",
        "value": "$9.40",
        "person": "Solarbreeze",
        "date": "6/17/2018",
        "stage": 3,
        "status": 0
    }, {
        "id": 10,
        "organization": "Livetube",
        "value": "$2.73",
        "person": "Holdlamis",
        "date": "2/3/2018",
        "stage": 0,
        "status": 1
    }, {
        "id": 11,
        "organization": "Meeveo",
        "value": "$1.60",
        "person": "Zamit",
        "date": "5/18/2018",
        "stage": 3,
        "status": 1
    }, {
        "id": 12,
        "organization": "Cogibox",
        "value": "$8.08",
        "person": "Pannier",
        "date": "9/21/2017",
        "stage": 3,
        "status": 1
    }, {
        "id": 13,
        "organization": "Skipfire",
        "value": "$9.65",
        "person": "Alpha",
        "date": "3/1/2018",
        "stage": 2,
        "status": 1
    }, {
        "id": 14,
        "organization": "Browsetype",
        "value": "$5.37",
        "person": "Flowdesk",
        "date": "4/1/2018",
        "stage": 0,
        "status": 1
    }, {
        "id": 15,
        "organization": "Talane",
        "value": "$6.94",
        "person": "Zaam-Dox",
        "date": "2/14/2018",
        "stage": 0,
        "status": 1
    }, {
        "id": 16,
        "organization": "Katz",
        "value": "$8.67",
        "person": "Duobam",
        "date": "3/7/2018",
        "stage": 3,
        "status": 1
    }, {
        "id": 17,
        "organization": "Tagpad",
        "value": "$3.20",
        "person": "Stim",
        "date": "6/17/2018",
        "stage": 2,
        "status": 0
    }, {
        "id": 18,
        "organization": "Lazz",
        "value": "$3.39",
        "person": "Tampflex",
        "date": "11/21/2017",
        "stage": 3,
        "status": 0
    }, {
        "id": 19,
        "organization": "Abata",
        "value": "$9.84",
        "person": "Span",
        "date": "12/26/2017",
        "stage": 0,
        "status": 1
    }, {
        "id": 20,
        "organization": "Fliptune",
        "value": "$4.92",
        "person": "Sonair",
        "date": "12/31/2017",
        "stage": 0,
        "status": 0
    }
];